<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_I forgot my password</name>
   <tag></tag>
   <elementGuidId>8490fc86-2779-4d47-87fa-fcca23e5658d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.checkbox.icheck > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='fm']/div[3]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57380199-ee11-42e9-b6b0-6df78b0a313a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://akademik.polban.ac.id/auth/forgot_password</value>
      <webElementGuid>e9b4a1af-4dd9-4841-af7f-ac8927c2810c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I forgot my password</value>
      <webElementGuid>c22d40cf-eb85-4b1f-a848-6b49dc0f9103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;checkbox icheck&quot;]/a[1]</value>
      <webElementGuid>c1fc3fd8-854f-4a6c-b268-149ec163e1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a97d9d16-fa50-4ad8-b979-9d6d5c9858ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://akademik.polban.ac.id/auth/forgot_password</value>
      <webElementGuid>3ced5677-b772-42e4-931e-338f1e50921d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I forgot my password</value>
      <webElementGuid>69d5d36f-5a76-46aa-8d1d-344d94d1299b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;checkbox icheck&quot;]/a[1]</value>
      <webElementGuid>26f18c5f-d58b-47af-80ea-4904fe63eecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c0da5ce-4c72-48ae-9818-50e48766b125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://akademik.polban.ac.id/auth/forgot_password</value>
      <webElementGuid>c919e5d0-e8b1-4e3f-a8a1-e05f0de934ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I forgot my password</value>
      <webElementGuid>e42c3d93-cf1e-4caa-8212-2bb6a9bef708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;checkbox icheck&quot;]/a[1]</value>
      <webElementGuid>400da658-8e08-439d-96a6-7fb626e77622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f4171e5-c898-43cb-9b3d-6028ff2c6acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://akademik.polban.ac.id/auth/forgot_password</value>
      <webElementGuid>8a241c6e-c7c1-46ac-bd3a-d4d22423d87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I forgot my password</value>
      <webElementGuid>26dedb47-4212-47c3-9f15-2d6acb67e63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;checkbox icheck&quot;]/a[1]</value>
      <webElementGuid>e1174b67-8e36-40e9-b402-770e99cffbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f7d533b-9673-495f-b63a-71fa07ad9b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://akademik.polban.ac.id/auth/forgot_password</value>
      <webElementGuid>df70921f-00da-48b1-8efc-0b8397bbd736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I forgot my password</value>
      <webElementGuid>759c7992-6854-4192-ba0e-e375978b0298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;checkbox icheck&quot;]/a[1]</value>
      <webElementGuid>e7d77d24-b420-4fb6-ae8f-2693edebfd8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7a8b3cb-034d-4b34-b4a6-5a2665a2a88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://akademik.polban.ac.id/auth/forgot_password</value>
      <webElementGuid>270361af-bcd1-4361-a8f9-9a14e9576432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I forgot my password</value>
      <webElementGuid>4780c64e-1b2c-45a3-b396-591b39a58591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;checkbox icheck&quot;]/a[1]</value>
      <webElementGuid>122fe86a-2663-43a3-9190-0b49dd1918f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2f6d103-e8dd-44e2-ac4b-dab8b5509e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://akademik.polban.ac.id/auth/forgot_password</value>
      <webElementGuid>ad361275-25e2-41ac-ae5c-ae2542712f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I forgot my password</value>
      <webElementGuid>29b69dfd-448b-4b32-851f-93140145ae1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;checkbox icheck&quot;]/a[1]</value>
      <webElementGuid>5ca69160-668b-46af-938a-5561491974c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ec584569-7a44-41b2-9509-1ff2079a0201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://akademik.polban.ac.id/auth/forgot_password</value>
      <webElementGuid>8278bddf-47d3-431d-beaf-5bb6ea8d8c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I forgot my password</value>
      <webElementGuid>761017be-917b-482b-ad3c-56d49d3c1810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-8&quot;]/div[@class=&quot;checkbox icheck&quot;]/a[1]</value>
      <webElementGuid>e541bfb1-30be-4fbb-b19a-770b0c9ea25d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='fm']/div[3]/div/div/a</value>
      <webElementGuid>36567f3e-f572-4f8c-8558-453fc94d1c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'I forgot my password')])[2]</value>
      <webElementGuid>3570cf44-4639-4fa4-aa41-89e168e50ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengesahan KRS'])[1]/following::a[1]</value>
      <webElementGuid>03a3c559-0dec-477d-a468-aa0e1b59546f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran Daftar Ulang'])[1]/following::a[1]</value>
      <webElementGuid>9c3ddf75-5c3b-4f40-85b3-aae0ecdae4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::a[1]</value>
      <webElementGuid>0989b4de-c047-4aa9-b843-fd72bdf792a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://akademik.polban.ac.id/auth/forgot_password')])[2]</value>
      <webElementGuid>72beaf53-43d2-4f1d-bd9e-70d0e5e3d20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>40306de4-0e5d-4b47-9ea9-492ddc912c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://akademik.polban.ac.id/auth/forgot_password' and (text() = 'I forgot my password' or . = 'I forgot my password')]</value>
      <webElementGuid>28e4f9dd-b071-4820-994b-c30a04cf29f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
