<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_JADWAL KEGIATAN</name>
   <tag></tag>
   <elementGuidId>2eaae77b-ca7d-4ea1-8637-10eda315763e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='akademik@polban.ac.id'])[1]/following::h2[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d4094ff7-4660-49ce-ada4-a2292099aed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>f791d9ba-f668-4af9-b9bd-eed46c44d6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>4fc7993e-34bf-41d5-a88f-34d62d2e5d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>bbb629cb-96cc-4d8e-8edb-3613bde6cd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>cbcbfcde-d120-4dfc-a5db-91f02d90ae67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>50108756-0851-48e5-80a9-d5ab932fabfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>6e92de41-2e9b-4a95-9841-70d45d460d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>1a6db22c-b58e-4b4d-9bd9-7c41c07afa98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e8b683e5-c2e6-4d4a-9414-109674f919a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>019eb303-52d1-49f0-924f-a4790112df6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>257184b1-e67e-4788-8971-7fa451f57255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>57f709bf-bb41-42b0-9729-858b3b3112b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c620aec6-8d91-48f2-9ede-cbc51bed210b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>1dc61c05-eb0e-4a9b-be4b-7f3fed2a127d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>22c9a8b1-d8a1-4396-a8ca-3ab8a9f50d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>caec7b4a-7aa4-4af0-8989-fa5d8c924826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e2db28f3-d46d-4b58-bf9c-3713a429db0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>3701ca70-bd41-4705-8d82-38952fdb1859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>f546023f-71d8-49e0-89f6-6ac326178a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>5be1bdee-02c3-41b0-887c-305b46893054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>7dac51f2-5f9b-4e46-943d-d6a96991d083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>87af6d9d-9954-4f49-94e5-1d1d54b66403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>25f33d57-1c7d-4b92-930e-16552fb7efab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>1c479b50-4f16-4598-a99a-a4915e96ec54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>54ffd5f5-d6c5-42cd-8a81-47d98523414b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>99b9fabf-c9ef-45c1-9ce6-f22d3219c228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>1cefc2c7-3dbc-4d0e-b678-c1de1cf8cd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>4d8b5887-c6ce-476f-a83c-8626a943dca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b247162c-83f7-4cc9-bd44-3b2077a664f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>f67c5a88-4a91-4dc9-ac5e-06a654e37511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>c8d2093c-fb5d-41ca-af81-68a8f69aa484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>80322c77-f7a4-4c7a-bc6d-26ee2e34df04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>164c8538-f0d1-4810-9033-be9a110d6ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>75cc5771-36c2-4259-9fe6-84c1aa37477f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>c2ce95e4-6431-4cc7-aca2-89e39392b1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>6db03bff-bdac-4fc6-891b-f263e724e05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c2b31693-1e1b-48a0-b027-ac2810166cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>e39b4c3a-4928-4431-b5e4-64cc74bac413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>6ed7c58c-57a3-4bed-a7ee-a5a9a371118f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>43c9d473-7f05-4f68-ba3c-384014eea53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>03f48978-e26a-45b3-aec2-2e28d0bb4261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>d6313412-84ea-4fe9-9a79-0fe05d596746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>a28321fb-60c6-488c-bf12-830c62970f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>4936850e-8850-4deb-ac00-992f49e17ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3d844a86-c27b-4c3c-b708-46d3ca549871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>0e1ed9bb-d4b5-4fa3-8c93-0d29b270a6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>cb9137f3-60d9-4ff4-9fc5-7e3b192bb683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>62ebd3b3-6eea-40aa-a017-c723e6abd987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>7a401fbf-a1f9-4a36-8ab6-fe3fd7428e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>7c0f2bfb-0d46-4ed9-98a7-f04fa3444909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>a8440c2a-71dc-453c-9a8b-4c6b72cd5519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>a6a337a2-e94f-4d6a-8458-9a15f283d21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c08105f3-e92d-4026-afe4-30e4fb7f07a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>4882b74f-2e4a-4608-96ae-f59892465364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>5b09c08b-0425-416f-bd45-2757c058e90c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>e0a7c8bb-67b0-4301-9d9c-38ea478ac487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>06c73529-c192-4ffc-9b87-11a6ea644fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>efb868bf-6306-4af7-9436-568c0f47d308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>f41a5b99-d493-4468-abbb-bcd915ccd02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>d9e74162-b481-4cbb-b5dc-e377cd793389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8255f65a-bad7-4fb5-8421-cda3f69cda83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>54549f14-b2bc-4c7e-9e3e-8cbc45800372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>ccc73b74-96da-432a-8f2c-bde0cfe1bafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>ffbbca86-a0c4-4a5e-8f2c-eaeeb24e5e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1e11b75f-ddaf-46ef-8351-caa2cc3a9633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>d2de62c3-ed94-4e47-b152-1b5ccee0ab58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>068d067d-7fe1-4c4a-833c-91127f3e17e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>14193c56-4454-403e-9ba1-ca308a34ca09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4ab5a080-2dcc-42ee-b6cf-060e9831de5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>7b315af2-e2ae-48dd-a207-b8741e0c9304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>115d8b92-7a57-46c6-91f1-3219b5dec4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>6fbdfb4b-53a8-4f16-998e-b4cf98126def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8ecb776b-405d-45d1-8be0-6735ffc48cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>24956f60-c6a6-43fd-b774-a13e1bc51e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>d06bc713-03be-472c-aa2e-76ee32a56038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>cadb86c8-fffb-4df6-99a9-49f341e05cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>31572b2a-bc01-40fc-9be8-6437f80497f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>935433be-55d3-4ee1-a19e-b6f4a581730e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>ee689de7-ab0d-4868-af9c-a2bf9eb7e819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>7de385fa-0c6f-4fc7-92f6-bf2b76608675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>7e243cae-e5d3-4ee7-98de-7897a94ed2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>cb6df975-5f76-458e-93e2-3e740cac68f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>90bd14cf-46ea-4e02-b534-8dab3d66cacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>c88098af-58ea-45fc-b1ad-3b03108e26cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>92358672-281c-4cae-8715-eefd8c1bb15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>4f4f1e17-2ab8-4ea6-99af-f29401176075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>5f7d13b5-4fbe-4823-b353-cef7936f0b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>47b266fb-54e9-480d-983c-96433ddb75af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>177dfb56-f664-47f2-8915-611effe1b918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>b78e30dc-85de-4318-bfe4-f9a4561159ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>6eb7f44f-2b07-4bdc-a1fd-eac064429158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>f09defdb-7e3f-4368-9760-37a3e56414de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>0d3ee55d-4d1b-4f58-aef1-20795fe3e9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>4126f0f4-9d75-4279-a6f8-0e0c152479c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>51886f98-d7cc-45df-b9df-2f2395924c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>06aee5f9-d0df-4c2c-97a2-cb185aa3f595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>2843499c-3d7e-4de9-9697-7d275cc9b070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>0e13f32b-d1ba-4fa1-a173-79b89793ae52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>b9c87dbc-1c7d-48f2-8680-fb67a7dba1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>3af5aafa-d629-488f-a2b6-b7d9c5c1c323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a6d129ad-6395-459f-ba0c-33f82f40cb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>bcefa038-69cf-4192-85bd-6e3b19146cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>58914d46-1296-4878-8463-c8851cf8c884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>87846b85-a1b5-4627-a094-e9422f32471c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f1703474-8111-4193-883b-bca38e115843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>957d0021-c3ab-42dc-b041-0d2e3efb955c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>ab2d0aba-3034-474e-950b-09050a0d08b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>268781da-7920-44f8-a90a-858e95cd7d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>dbe4407e-1868-4eec-a505-8be54efb814b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>6c25bd02-1e5a-4ebc-bb53-a89083cf06dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>99a9d30a-df97-45dd-ba7e-237338f288bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>974e29e9-bee5-4978-89df-3b56faaf9c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a7d57652-21da-493e-81c8-fda6afb2664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>ac2486a0-df88-4e84-b1ba-658da227c64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>f0f7bf0d-10f3-4dd3-9c0f-715fac79c2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>95f47751-8116-4328-b2dc-6cebf8008883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>875b88b7-3d98-42d0-aa74-9e78a390357a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>aa3154df-7bb6-4720-869c-550562be2507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>2f449dfe-0d46-4c0c-b541-3c0c92e0c7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>6ddd5f28-16cc-4cfc-9b60-1080837d5c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3301d068-79be-4a1a-8198-a4c0b5c3da2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>6bab9bf0-fea4-4281-bfb8-568fca5b8d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>027791d4-b12f-4cb9-922d-4879fcec37dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>7ffa19a4-7e8d-490c-8ca1-732afcf991a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>182f60bb-6395-4bbe-9713-c5616a240b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>2a658d6a-7a20-4cd9-a4a3-82dbe1f5976f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JADWAL KEGIATAN</value>
      <webElementGuid>a827ba0f-0434-4458-8f7c-3fb77fb005ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>2d1a9d2f-19b8-4135-a986-e70179568298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='akademik@polban.ac.id'])[1]/following::h2[1]</value>
      <webElementGuid>cedc05b0-03ea-49c6-a685-7bef8f09a9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='permasalahan data'])[1]/following::h2[1]</value>
      <webElementGuid>1e64cd99-001d-44f0-855b-af3242340573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengisian Kuesioner Dosen'])[1]/preceding::h2[1]</value>
      <webElementGuid>0d0998a9-0440-4158-9a0b-79cc8a5ae0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahasiswa mengisi Kuesioner Dosen pada menu yang telah disediakan'])[1]/preceding::h2[1]</value>
      <webElementGuid>b0b94a8c-5bff-4ff0-b023-113bb0713dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JADWAL KEGIATAN']/parent::*</value>
      <webElementGuid>4509e787-e88e-4d21-9331-859f2e1a00eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2</value>
      <webElementGuid>afc44897-ff83-4369-a269-f562550a4469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'JADWAL KEGIATAN' or . = 'JADWAL KEGIATAN')]</value>
      <webElementGuid>9e8f4fe0-8ab0-4889-bc86-d49c8e1be37b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
