<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_PANDUAN LOGIN APLIKASI AKADEMIK</name>
   <tag></tag>
   <elementGuidId>92bb8673-bffd-48ee-b5a1-c292522bc201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.box-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::h2[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>2f1f427f-cfcd-4554-9924-e06d2a15aaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>a5063863-1308-4f7a-8861-e0290004c1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>c6916feb-5af1-4faf-a909-0624dda0ad7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>fad2dbab-79e7-4c23-bcdf-31193fbc2f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>ac2fe263-e10d-4904-b6b7-ee3f456f644e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>ce61520b-b331-4c8c-bc15-e66fc1b4b02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>ba9c778b-22f9-4761-b581-06d70dd2866d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>7932877f-2d02-43e8-8893-9012b48e9e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>6ef49ce7-7c91-43a1-9dac-85f499143b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>61898dcb-0817-4fe4-9d87-dc6e29e68272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>28af0b4c-9bda-4e14-9d10-418df3fedff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>73e20b11-2014-485c-895c-b80e281691e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>936a2f38-f72f-4a8b-833f-43995874e7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>d87a1159-be09-441a-832a-1b8d0c6adaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>846ddac1-4e10-445f-afb2-926371e12f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>696d1fe8-2007-461d-8a0d-1cb02d3cffee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b2c71307-a629-498a-8f2a-313f45709dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>d8cb6dd0-cc44-4507-bf27-9f41e76aca60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>652dcf57-0fcc-4e11-bf36-dcb9b4657802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>ec07f0f8-b9c2-4ccc-9712-441c438e5eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>08392aa0-83e4-4106-a64a-8f9fcc864f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>25b76ffb-0f30-41ef-ad79-aac59b597a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>7eb52b31-9edf-4cc0-81ad-3732d69b3749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>3f1fd91f-6c58-4449-8fef-d374515bd7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b858a832-297c-4013-8a0f-de995f2810f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>d7dc1969-502c-44f2-898b-6299e943c55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>70ae46d2-92a3-4a5c-8188-ecb71463153c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>6d184c7d-6d59-48e7-a31e-eeec2784355a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c844a404-6e83-4615-8a67-601d916c2d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>0988ef62-75d7-4457-88f9-8abb029c99bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>f3251602-0d02-402e-94df-85aad0d457fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>9c80180d-b37a-4b07-a67e-9bffdda97b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e4e4fea0-d0bb-4312-84a9-9f6094ed7121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>23883852-2d35-4add-ac91-22b2c76ced43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>a767d605-e78a-4111-8837-50aec7a3b388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>265f8fc2-4307-464c-b2f8-fe82fd5c7bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1ee5e793-d483-4785-9a99-d5c03664c772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>51726e7c-b5bd-42c7-ba3e-86d9d88f2c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>35dced55-67eb-4a1d-a635-cbc80f799ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>c7c85789-b4f6-49fd-a88f-a4fb895b1f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>cb38adad-f0b5-4833-b5bf-d552d0ce8669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>740b831f-690c-40c6-a7ec-d2d23908d32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>65fe77b2-f87b-4922-beef-3e3ac1fcd5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>b8b3ac95-0967-471e-b445-7042470088b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f88f6b8e-253a-4361-aa2c-7bc6741489c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>5cd6a4cc-b332-4bf3-b470-b5dbda837a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>ffa6c133-24df-469d-b1f5-fa33570390d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>8f228ddf-9439-4c53-9ea4-363d94b7ac01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e766bb7d-ad65-48ce-b97c-55173e9d47af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>d7419a3c-b75b-49ce-8812-0fe45206dbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>90476a9f-3361-40bc-982c-2e68206f95a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>2bfc83e7-257a-47e4-869a-62512920edaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>e445708c-70c6-4748-afa0-afe36ea1df03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>58806cbc-c77f-49ff-981a-fe1eb05f623b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>e1cd8a77-ae25-43bc-824c-c9be7a7e6481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>8282cae7-bf5f-4279-a7c1-993bec6ac1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>03588c6e-ac5c-4051-a5db-a522f4c6fd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>1eea2e46-fc59-402c-b817-083e275e1641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>c6fc5e16-15a7-48c0-b458-054569b296b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>c47be74f-0527-4d63-8dd8-8a8c8c717534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4ee8c5e4-55d8-4f7a-bf9d-ae5fcb0dfccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>c8078de4-3289-444b-87a1-2bb865b6e4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>260d1256-df9a-4e52-a610-3efb1481963e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>37bc4eca-99d8-458b-a86e-da431210654b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>428f281e-c5ea-4a9a-a2b2-84f255c8989b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>e76913dd-e2f7-4b4f-8772-a4352418cd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>5fd70aa6-a0aa-4146-bb4f-e348c4ddb9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>ad1a5083-6f9e-4a7f-bebe-3625fd2ea61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>50fd36da-8227-4405-9878-e81ca5d254c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>97cf6be4-2884-4054-9425-8ee184707b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>fd923093-555c-4aff-ad55-c250f68a0f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>40826766-ed03-4cbb-8dfa-3b4c7a0b6e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>21d13d96-dcce-457e-ba4f-4fbcf3020a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>ea6185da-eab3-4e0c-8bf4-0c1cc0c36d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>40c6a1c1-2007-479a-a34a-89ec4e413c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>295a54b4-63d3-46d5-90ae-d12a82f95996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d6c029d2-a2c5-4e35-930c-3a3b5511700c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>33f49cf6-cde9-4b4a-824e-33159fc6005b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>ac0ccdfe-eac1-4f8c-bacc-60372915c1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>6dd9d3e9-cd27-4f04-be65-ffd6e1ea382d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>be1bd801-edf6-4c88-add7-ef711653c503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>270270b3-4157-41a3-b81e-9eaebe53e653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>ecbcd693-d7cf-4bad-900a-191284fb4002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>277b1bfa-bc58-4cba-9905-8d3ba306d010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>9691a5b1-79e8-4b19-b7b0-7010cd90ca1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>efdf0739-60e8-4d0f-ad62-79d2e98c2f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>4bc7c946-5043-40bf-93ac-f6e033ceecc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>8016bf15-22c5-4412-a114-cf8ad4a1864a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>939f2c54-2e45-4c69-950b-7d335d0933c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>050ee47a-b5e3-44a5-9e7b-9051a12aaa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>06a73d36-1d31-4d7c-9227-c1b8291ca6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>0e61cc73-b4a4-42f4-88ce-2243085d4621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b2b0b093-e8c6-4543-be84-3150a02b80d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>e317513d-217f-4cda-b5d9-e149733d1659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>f8705f02-ce4c-4a12-8b03-52fa0d7b6a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>4cb54425-c52e-467e-adaf-2a38184447b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>abf1ea99-a6af-4f6f-b71c-da9a10ab3d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>872fc900-5626-438b-bc22-bc69232070db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>7c51b67a-0c06-46f8-8fde-95942e8dc7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>316dd9b8-009e-4dda-b92e-6b967cf082dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>35fc1fb5-530e-47ea-98e0-100efb545752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>be640c7f-a36c-4b95-b966-0bf290f98f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>f7146ee8-f156-4faf-b2fa-ec0f60a95811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>0d4286f6-d96b-4755-b327-46a08a5ffb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>590acb16-287c-417b-a8a5-b50afb41ce47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>851bc2c3-ac35-4cf4-a89b-14e598bec719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>22439760-92fc-459a-a0bf-6030782cbac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>30271d10-9150-4ced-b4aa-af044bcac040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>16c17ab6-5dd3-4512-a3b2-1db971868956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>e50f669d-4c1e-4fc8-8f7e-eac0323e1ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>cec45c59-22b7-4398-a66b-5473dac5d52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>b7b4a086-7c25-486f-b4d0-373ecd8aaae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>828c26ed-38cf-4649-b6eb-aac588e32108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>1b43b338-a3de-44fa-b5e4-09bfba6e8bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>7bc8026b-f430-4425-934c-d0896463c394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>b2c703d8-2665-4206-8c92-9e7ef6fb4a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>048f084e-9167-4814-9114-b906eec27f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>d13012fc-6aee-4aa9-9ba3-6fe2dc75fd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>2167032c-b9d6-4b6d-9702-b3ace49caf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>35ba3df9-ceb8-4df7-a4b1-b6e01191e462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>9e69f33f-f697-46b5-87f3-8a6f12b7051d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>334c4b50-9b77-4a54-a2c3-b63c183a394f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>4f0096c7-cf47-4e84-8924-e3084acc6b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>740ef1bf-2c28-4abe-b173-cb003488a7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>739fc81b-7995-45d6-a1ee-9fb844c14f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-title</value>
      <webElementGuid>f772234c-f3b0-42ed-ad3d-db84418571e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANDUAN LOGIN APLIKASI AKADEMIK</value>
      <webElementGuid>aa648f7e-e5b2-415e-8ac6-623ec1108585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-page&quot;]/div[@class=&quot;login-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;box box-default collapsed-box&quot;]/div[@class=&quot;box-header with-border&quot;]/h2[@class=&quot;box-title&quot;]</value>
      <webElementGuid>e6094775-fb48-4471-be47-d89a0aedd21f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/preceding::h2[1]</value>
      <webElementGuid>7794d211-db9d-4207-a194-2131c51ac126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PANDUAN LOGIN APLIKASI AKADEMIK']/parent::*</value>
      <webElementGuid>c73b643a-53bc-49ec-9cab-6e9fc47b1610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>91fb7f4f-14f8-41d2-80c7-147eff1af9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'PANDUAN LOGIN APLIKASI AKADEMIK' or . = 'PANDUAN LOGIN APLIKASI AKADEMIK')]</value>
      <webElementGuid>9f271240-bed9-4578-84f1-e2039c437d3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
